from typing import Any


def clear() -> None: ...
def move(direction: str) -> None: ...
def tile() -> Any: ...
def plant(id: str) -> None: ...
def harvest() -> None: ...
def abs(num: Any) -> Any: ...
def can_harvest() -> bool: ...
def can_move(direction: str = ...) -> bool: ...
def change_hat(hat: str) -> None: ...
def do_a_flip() -> None: ...
def get_companion() -> Any: ...
def get_entity_type() -> str | None: ...
def get_ground_type() -> str | None: ...
def get_pos_x() -> int: ...
def get_pos_y() -> int: ...
def get_tick_count() -> int: ...
def get_time() -> float: ...
def get_water() -> int: ...
def get_world_size() -> int: ...
def has_finished() -> bool: ...
def len(obj: Any) -> int: ...
def list(obj: Any = ...) -> list[Any]: ...
def max(obj: Any) -> Any: ...
def max_drones() -> int: ...
def measure() -> Any: ...
def min(obj: Any) -> Any: ...
def num_drones() -> int: ...
def num_items(item: str | None = ...) -> int: ...
def num_unlocked(unlock: str | None = ...) -> int: ...
def pet_the_piggy() -> None: ...
def print(obj: Any = ...) -> None: ...
def quick_print(obj: Any = ...) -> None: ...
def random() -> float: ...
def range(start: int, stop: int | None = ..., step: int | None = ...) -> Any: ...
def set_execution_speed(speed: int) -> None: ...
def set_world_size(size: int) -> None: ...
def spawn_drone(fn: Any, *args: Any) -> Any: ...
def str(obj: Any = ...) -> str: ...
def swap(a: Any, b: Any) -> None: ...
def tap(x: int, y: int) -> None: ...
def till(x: int | None = ..., y: int | None = ...) -> None: ...
def use_item(id: str, amount: int | None = ...) -> None: ...
def wait_for(condition: Any) -> None: ...


East: str
West: str
North: str
South: str


class Entities:
    Apple: str
    Bush: str
    Cactus: str
    Carrot: str
    Dead_Pumpkin: str
    Dinosaur: str
    Grass: str
    Hedge: str
    Pumpkin: str
    Sunflower: str
    Treasure: str
    Tree: str


class Items:
    Hay: str
    Wood: str
    Carrot: str
    Pumpkin: str
    Cactus: str
    Bone: str
    Weird_Substance: str
    Gold: str
    Water: str
    Fertilizer: str
    Power: str


class Unlocks:
    Cactus: str
    Carrots: str
    Debug: str
    Debug_2: str
    Dinosaurs: str
    Expand: str
    Expand_2: str
    Fertilizer: str
    Functions: str
    Grass: str
    Hats: str
    Lists: str
    Loops: str
    Mazes: str
    Megafarm: str
    Operators: str
    Plant: str
    Polyculture: str
    Pumpkins: str
    Senses: str
    Speed: str
    Sunflowers: str
    Timing: str
    Trees: str
    Utilities: str
    Variables: str
    Watering: str


class Hats:
    Gray_Hat: str
    Purple_Hat: str
    Green_Hat: str
    Brown_Hat: str
    Dinosaur_Hat: str


class Grounds:
    Soil: str
    Sand: str
    Grass: str
    Stone: str
    Water: str
